version: "3.8"

services:
  postgresuser:
    image: postgres:latest
    container_name: postgres_user_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: keycloakuser
    volumes:
      - ./seeder/init-users.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-volume\KeycloakUser:/var/lib/postgresql/data
    networks:
      - keycloak-network

  postgresserver:
    image: postgres:latest
    container_name: postgres_server_container
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: keycloak
    command: -p 5433
    volumes:
      - ./seeder/init-default-postgre.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker-volume\KeycloakServer:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
    external: true
